import express from 'express';
const router = express.Router();
import forumController from "../controllers/forumController.js";
import loginCheck from '../middlewares/loginCheck.js';

router.get('/', forumController.getAllDoc);
router.post('/user/login', forumController.login);
router.post('/create-acc', forumController.createAcc);
router.get('/password/forget', forumController.forgetPasswordPage);
router.post('/password/forget/generate', forumController.forgetPasswordGenerate);
router.post('/password/forget/verify', forumController.forgetPasswordVerify);
router.post('/password/change', forumController.changePassword);
router.post('/checkuname',forumController.check_uname);
router.get('/email/:email', forumController.checkEmail);
router.post('/contact_form',forumController.contactform);
router.get('/logout', forumController.logout);
router.get('/catogories', forumController.catogories);
router.get('/catogories/:cat_name', forumController.one_catogories);
router.post('/catogories/:cat_name', forumController.question_post);
router.get('/forum/question/:id', forumController.forum_answers);
router.post('/post/answers', forumController.post_answers);
router.delete('/question/delete', forumController.deleteQuestion);
router.delete('/answer/delete', forumController.deleteAnswers);
router.patch('/api/likes',forumController.manageLikes);
router.get('/search/:searchTxt', forumController.search);
router.get('/question/update/:questionId', forumController.updateQuestionPage);
router.post('/question/update/', forumController.updateQuestion);
router.get('/chatroom/:roomtype', loginCheck, forumController.chatRoom);
router.all('*', forumController.notfound);
export default router;